name: 'frosty'
version: '1.0.0'
config-version: 2

# Setup profile for re_data in your ~/.dbt/profile.yml file
profile: 'frosty'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets: ["target", "dbt_modules", "dbt_packages"]

query-comment:
  comment: "comment {{ dbt_version }}"
  append: true

#models: 
  # dbt_artifacts:
  #   +docs:
  #     show: false
  # dbt_utils:
  #   +docs:
  #     show: false
  # dbt_artifacts:
  #   +schema: dbt_artifacts
  #   staging:
  #     +schema: dbt_artifacts_stg

